### PR TITLE
added Rain Dark theme

### PR DESCRIPTION
**Pull request by rishav12s**
new theme "Rain Dark"

### CODE REVIEW

**Comment by kRHYME7** [comment]
Try to not hardcose the font size please.  

https://github.com/rishav12s/Rain-Dark/blob/9c07c073d151700922179cd10df7fcb128d2827f/Configs/.config/hyde/themes/Rain%20Dark/rofi.theme#L11C1-L11C31

This cause  rofi to be scaled inconsistently

**Comment by rishav12s** [comment]
dracula theme had that and it looks nice ngl 

should i remove that then ?

**Comment by kRHYME7** [comment]
> dracula theme had that and it looks nice ngl

@rishav12s  one of the reasons why it looked awkward on multiple monitors.  Did not notice it earlier, that's why I'm trying to test all themes that passes here.

**Review by kRHYME7 — APPROVED** [review]
Should work perfectly with the CLI now. 

Do the hustle of maintaining it please 💫 
Thank!

**Comment by rishav12s** [comment]
ok no problem just edited it hope now it can be merged 

and could you please some screenshots of the theme from your setup my laptop has a very low res of 1366x768 so they are of not good quality

**Pull request merged**
