### PR TITLE
Readme Renovation

### PR DESCRIPTION
**Pull request by abenezerw**
alphabetical.
prettier.
still have themes left cause i don't remember their colors.

also to edit the black and whites. its as easy as changing the color hex codes or names within right on the link.
** for themers that want to edit their theme-tag colors to be more precise with their theme.**

### CODE REVIEW

**Comment by kRHYME7** [comment]
Thanks! Can try to check the directory for the preview and decide for the hex color.

**Comment by abenezerw** [comment]
we all good now. and i was also thinking of putting the theme-tags inside the table accordingly. and maybe reusing all the links so on-click you go to the repo. then we can reduce the link table

**Comment by abenezerw** [comment]
1. More changes including deprecation of old patch for import
2. Usage section for a step by step
       .1   I recommend just using 'Hyde theme import' without the arguments to make it simple
       .2   Also wanted to clean out the note part just for a general clean look
3. Also recommend naming the repo "Hyde-Themes". I know there's an official one by tittu, but feels confusing there being a theme and a gallery.
4. I don't know if the about section also updates in here. but maybe add the link to the main repo as a site like my fork.

**Comment by kRHYME7** [comment]
> .1 I recommend just using 'Hyde theme import' without the arguments to make it simple

We can say "Advance" options though
image


> .2 Also wanted to clean out the note part just for a general clean look

Should be fine. 

> Also recommend naming the repo "Hyde-Themes". I know there's an official one by tittu, but feels confusing there being a theme and a gallery.

I preferred "gallery" as collection/ of themes. Something like a thumbnail of the real thing


> I don't know if the about section also updates in here. but maybe add the link to the main repo as a site like my fork.

You can link it in the Descriptions for now.  
Do you happen to have some knowledge about making a webpage still hosted by github. Example the hyprland wiki style. I think it's a markdown.

**Comment by kRHYME7** [comment]
Tell me if this is ready for merge

**Comment by abenezerw** [comment]
1. Used 'Additional' instead of 'Advanced'
2. Deleted 'Notes' part
3. gallery it is then. i also tried adding the world hyde gallery into the banner to change it out but sort of low quality. you can look at it. in the directory HydeThemesbanner.png
4. I meant link as in the whole gallery on the about section instead of the particular themes. just incase someone walks in here without looking at Hyde first.

**Comment by abenezerw** [comment]
And i think wiki.hyprland.org is a full on javascript library site. written in express i think. 
github pages only accept html files. but i can try to make something. what were you thinking?

**Comment by kRHYME7** [comment]
Just to showcase these themes. But I guess Readme will suffice.

**Comment by abenezerw** [comment]
Ill look into it, but in the meantime. This is ready to merge.

**Pull request merged**
